# Generated by Django 2.2 on 2021-05-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoot',
            options={'ordering': ['-id']},
        ),
    ]
