# Generated by Django 2.2 on 2021-05-13 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoots', '0003_hoot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HootLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoots.Hoot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hoot',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='hoot_user', through='hoots.HootLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
