# Generated by Django 2.2 on 2021-05-14 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoots', '0004_auto_20210512_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoot',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoots.Hoot'),
        ),
    ]
